# This is a config file for the models available in HarmBench. The entries in this config specify model names, how to load the models, how many GPUs
# to request for the models (e.g., if using SLURM), the model type, and other information.

# ===================== Documentation for the fields ===================== #
# Required fields for all models::
#     model_type: The type of model. This can be "open_source", "closed_source", "open_source_multimodal", or "closed_source_multimodal".
#                 All models are required to have this field in their config. This is used to determine which other fields to expect.

# Required fields for open_source models::
#     model: A dictionary containing arguments to load_model_and_tokenizer in `HarmBench/baselines/model_utils.py`. This is used to load the model
#            and tokenizer. This dictionary is required to have the `model_name_or_path` field. Other fields are optional and can be used to
#            override the default arguments to load_model_and_tokenizer.
#     num_gpus: The number of GPUs to request for the model. This is used to determine the number of GPUs to request when using SLURM.
#               Some methods also load open source LLMs using vLLM or create mini-clusters using ray. For these methods, we use `num_gpus`
#               to allocate the right number of GPUs for the model.
#               NOTE: The default values were chosen to work with 80GB A100 GPUs. If you are using different GPUs, you may need to adjust `num_gpus`.
# 
# Required fields for closed_source models::
#     model: A dictionary containing arguments to load_model_and_tokenizer in `model_utils.py`. This is used to load the model and tokenizer.
#            This dictionary is required to have the following fields, which are handled in `HarmBench/api_models.py`:
#            - model_name_or_path: The name of the API. This is used to select the API class in `HarmBench/api_models.py`.
#            - token: The token for accessing the model
#
# Required fields for open_source_multimodal models::
#     model: A dictionary containing arguments to load_model_and_tokenizer in `HarmBench/baselines/model_utils.py`. This is used to load the model and tokenizer.
# 
# Required fields for closed_source_multimodal models::
#     model: A dictionary containing arguments to load_model_and_tokenizer in `model_utils.py`. This is used to load the model and tokenizer.


# ===================== Open-Source Multimodal Models ===================== #

llava_v1_5:
  model:
    model_name_or_path: LLaVA_v1_5
  model_type: open_source_multimodal
  num_gpus: 1

llava_v1_5l:
  model:
    model_name_or_path: LLaVA_v1_5L
  model_type: open_source_multimodal
  num_gpus: 1

llava_v1_6:
model:
  model_name_or_path: LLaVA_v1_6
model_type: open_source_multimodal
num_gpus: 1

instructblip:
  model:
    model_name_or_path: InstructBLIP
  model_type: open_source_multimodal
  num_gpus: 1

qwen_vl_chat:
  model:
    model_name_or_path: Qwen_VL_Chat
  model_type: open_source_multimodal
  num_gpus: 1

minigpt4:
  model:
    model_name_or_path: MiniGPT4
  model_type: open_source_multimodal
  num_gpus: 1


# ===================== Closed-Source Multimodal Models ===================== #
